# Port Number Configuration
server:
  port: 9090

# Actuator Configuration
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

# Image Folder
project:
  image: images/
  
  
# Database Configurations
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: manager
    url: jdbc:mysql://localhost:3306/blogdb
    username: root
    
# date format
  jackson:
    date-format: yyyy-MM-dd
    
# JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    
# Image Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
